### ISSUE TITLE
Roadiz alpha release todo

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#36]
- [x] Domain names
- [x] Github name
- [x] Pass Insight and Travis
- [x] Get a clean Docker image (with Solr)
- [x] Create Sami and ReadTheDocs headers
- [x] Create Roadiz website
- [x] Harmonize headers on Roadiz websites (docs, api)
- [x] Get CMS contacts and prepare a pretty newsletter
- [x] Set version number on Backoffice and connexion form and Install theme
- [x] Test zip install on shared hosting
